apiVersion: v1
kind: Service
metadata:
  name: admin-api-service
  namespace: admin
spec:
  type: ClusterIP
  selector:
    name: callbook
  ports:
  - name: admin-api-request
    port: 1002
    targetPort: 1005