apiVersion: apps/v1 
kind: Deployment
metadata:
  name:  mongo-db
  namespace: db
  labels:
    name: callbook
spec:
  replicas: 1
  selector:
    matchLabels:
      name: callbook
  template:
    metadata:
      labels:
        name: callbook
    spec:
      containers:
      - image: mongo:4.2.24-bionic
        name: mongo-db
        resources:
          requests:
            cpu: "25m"
            memory: "125M"
          limits: 
            cpu: "50m"
            memory: "250M"  
        env:
        # - name: MONGO_INITDB_ROOT_USERNAME
        #   value: mongoadmin
        # - name: MONGO_INITDB_ROOT_PASSWORD
        #   value: secret
        # - name: MONGO_INITDB_ROOT_DB
        #   value: my_db
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysecrets
              key: MONGO_INITDB_ROOT_USERNAME
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecrets
              key: MONGO_INITDB_ROOT_PASSWORD
        - name: MONGO_INITDB_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysecrets
              key: MONGO_INITDB_DATABASE   
        ports:
        - containerPort: 27017