apiVersion: apps/v1 
kind: Deployment
metadata:
  name:  mongo-db
  namespace: default
  labels:
    name: callbook
spec:
  replicas: 2
  selector:
    matchLabels:
      name: callbook
  template:
    metadata:
      labels:
        name: callbook
    spec:
      containers:
      - image: mongo:4.2.24-bionic
        name: mongo-db
        resources:
          requests:
            cpu: "25m"
            memory: "125M"
          limits: 
            cpu: "50m"
            memory: "250M"  
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: mongoadmin
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: secret
        - name: MONGO_INITDB_ROOT_DB
          value: my_db   
        ports:
        - containerPort: 27017