apiVersion: v1
kind: Service
metadata:
  name: user-ui-service
  namespace: user
spec:
  type: LoadBalancer
  selector:
    name: callbook
  ports:
  - name: user-ui-request
    port: 3001
    targetPort: 3000