apiVersion: apps/v1
kind: Deployment
metadata:
  name: callbook-user-ui

  namespace: default
  labels:
    name: callbook-user-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      name: callbook-user-ui
  template:
    metadata:
      labels:
        name: callbook-user-ui
    spec:
      containers:
      - image: us-east1-docker.pkg.dev/kubernetes-389210/callbooking/user-ui
        # imagePullPolicy: IfNotPresent
        # command: [ "/bin/bash", "-c", "--" ]
        # args: [ "while true; do sleep 30; done;" ]
        name: user-ui
        resources:
          requests:
            cpu: "25m"
            memory: "125M"
          limits: 
            cpu: "50m"
            memory: "250M"  
        ports:
        - containerPort: 3000
