apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-ui
  namespace: user
  labels:
    name: callbook
spec:
  replicas: 1
  selector:
    matchLabels:
      name: callbook
  template:
    metadata:
      labels:
        name: callbook
    spec:
      containers:
      - image: us-east1-docker.pkg.dev/kubernetes-389210/callbooking/user-ui:1.0
        #imagePullPolicy: IfNotPresent
        # command: [ "/bin/bash", "-c", "--" ]
        # args: [ "while true; do sleep 30; done;" ]
        name: user-ui
        resources:
          requests:
            cpu: "200m"
            memory: "400Mi"
          limits: 
            cpu: "400m"
            memory: "800Mi"
        env:
        - name: REACT_APP_API_URL
          value: http://10.40.15.93:1003
        ports:
        - name: user-ui-port
          containerPort: 3000
