apiVersion: v1
kind: Service
metadata:
  name: user-api-service
  namespace: user
spec:
  type: ClusterIP
  selector:
    name: callbook
  ports:
  - name: user-api-request
    port: 1003
    targetPort: 1004