apiVersion: v1
kind: Service
metadata:
  name: user-api-service
spec:
  type: ClusterIP
  selector:
    name: callbook
  ports:
    - name: user-api-service-port
    - targetPort: 1004
      port: 1004